### ISSUE TITLE
Figure colors and markers are not unique

### ISSUE THREAD

**Issue by hombit** [kboone/parsnip#4]
I'm not sure this is the real issue and you'd like to fix it, but it is a bit confusing that different instruments have the same colors and markets. Moreover, PS1 r (and LSST r) has the same color/marker as ZTF g and vice versa

**Comment by kboone** [comment]
This is a tricky one. Individual light curves typically don't include observations from multiple instruments, so I was treating them all separately when I chose colors. There was an unintentional bug where the ZTF g and r were flipped that I fixed. The ZTF and PS1 colors should now be identical. PLAsTiCC has extra bands, so it still doesn't match up...

It might makes sense to choose a color based off of something like the band's central wavelength using some spectral colormap. I've tried things like that in the past, but you end up getting weird color combinations that don't look that great. Hand-chosen colors are the best solution that I have come up with for now. If you have a better alternative I'd be very interested.

Note that you can also override the default colors in ParSNIP by updating the `parsnip.band_info` dictionary before you make a plot. See `instruments.py` for its structure.

**Comment by hombit** [comment]
I agree with you, and thank you for this advice!
